services:
  api-exchange:
    build:
      dockerfile: orderPunching.Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - logs_dbx:/app/logs_data
    network_mode: host

  order-matching:
    build:
      dockerfile: orderMatching.Dockerfile
    depends_on:
      - api-exchange
    env_file:
      - .env
    volumes:
      - logs_dbx:/app/logs_data
    network_mode: host

  state-manager:
    build:
      dockerfile: stateManager.Dockerfile
    depends_on:
      - api-exchange
    env_file:
      - .env
    volumes:
      - logs_dbx:/app/logs_data
    network_mode: host

  frontend:
    build:
      dockerfile: frontend.Dockerfile
    depends_on:
      - api-exchange
    ports:
      - 3000:80


volumes:
  logs_dbx:
    driver: local
